// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PrimeNumberDecomposition/PrimeNumberDecompositionpb/PrimeNumberDecomposition.proto

package PrimeNumberDecompositionpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimeNumberDecompositionRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompositionRequest) Reset()         { *m = PrimeNumberDecompositionRequest{} }
func (m *PrimeNumberDecompositionRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionRequest) ProtoMessage()    {}
func (*PrimeNumberDecompositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_472e5ae3a6d7119a, []int{0}
}

func (m *PrimeNumberDecompositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompositionRequest.Unmarshal(m, b)
}
func (m *PrimeNumberDecompositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompositionRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDecompositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompositionRequest.Merge(m, src)
}
func (m *PrimeNumberDecompositionRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompositionRequest.Size(m)
}
func (m *PrimeNumberDecompositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompositionRequest proto.InternalMessageInfo

func (m *PrimeNumberDecompositionRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberDecompositionResponse struct {
	PrimeFactor          int64    `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor,proto3" json:"prime_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompositionResponse) Reset()         { *m = PrimeNumberDecompositionResponse{} }
func (m *PrimeNumberDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionResponse) ProtoMessage()    {}
func (*PrimeNumberDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_472e5ae3a6d7119a, []int{1}
}

func (m *PrimeNumberDecompositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompositionResponse.Unmarshal(m, b)
}
func (m *PrimeNumberDecompositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompositionResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDecompositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompositionResponse.Merge(m, src)
}
func (m *PrimeNumberDecompositionResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompositionResponse.Size(m)
}
func (m *PrimeNumberDecompositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompositionResponse proto.InternalMessageInfo

func (m *PrimeNumberDecompositionResponse) GetPrimeFactor() int64 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

func init() {
	proto.RegisterType((*PrimeNumberDecompositionRequest)(nil), "PrimeNumberDecomposition.PrimeNumberDecompositionRequest")
	proto.RegisterType((*PrimeNumberDecompositionResponse)(nil), "PrimeNumberDecomposition.PrimeNumberDecompositionResponse")
}

func init() {
	proto.RegisterFile("PrimeNumberDecomposition/PrimeNumberDecompositionpb/PrimeNumberDecomposition.proto", fileDescriptor_472e5ae3a6d7119a)
}

var fileDescriptor_472e5ae3a6d7119a = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x0a, 0x0a, 0x28, 0xca, 0xcc,
	0x4d, 0xf5, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x72, 0x49, 0x4d, 0xce, 0xcf, 0x2d, 0xc8, 0x2f, 0xce,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0xc7, 0x25, 0x51, 0x90, 0x84, 0x53, 0x4a, 0xaf, 0xa0, 0x28, 0xbf,
	0x24, 0x5f, 0x48, 0x02, 0x97, 0xbc, 0x92, 0x25, 0x97, 0x3c, 0x2e, 0xb9, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0x3c, 0xb0, 0xac, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73,
	0x10, 0x94, 0xa7, 0xe4, 0xca, 0xa5, 0x80, 0x5b, 0x6b, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90,
	0x22, 0x17, 0x4f, 0x01, 0x48, 0x4d, 0x7c, 0x5a, 0x62, 0x72, 0x49, 0x3e, 0xcc, 0x04, 0x6e, 0xb0,
	0x98, 0x1b, 0x58, 0xc8, 0x68, 0x27, 0x23, 0x6e, 0x27, 0x04, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7,
	0x0a, 0x4d, 0x65, 0xe4, 0xc2, 0xe9, 0x05, 0x21, 0x4b, 0x3d, 0x9c, 0xbe, 0x27, 0xe0, 0x35, 0x29,
	0x2b, 0x72, 0xb4, 0x42, 0xbc, 0xa6, 0xc4, 0x60, 0xc0, 0xe8, 0x24, 0x13, 0x25, 0x85, 0x3b, 0x52,
	0x92, 0xd8, 0xc0, 0x81, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x92, 0x7d, 0x03, 0xd2,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrimeNumberDecompositionServiceClient is the client API for PrimeNumberDecompositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberDecompositionServiceClient interface {
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (PrimeNumberDecompositionService_PrimeNumberDecompositionClient, error)
}

type primeNumberDecompositionServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrimeNumberDecompositionServiceClient(cc *grpc.ClientConn) PrimeNumberDecompositionServiceClient {
	return &primeNumberDecompositionServiceClient{cc}
}

func (c *primeNumberDecompositionServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (PrimeNumberDecompositionService_PrimeNumberDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberDecompositionService_serviceDesc.Streams[0], "/PrimeNumberDecomposition.PrimeNumberDecompositionService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberDecompositionServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberDecompositionService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeNumberDecompositionResponse, error)
	grpc.ClientStream
}

type primeNumberDecompositionServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *primeNumberDecompositionServicePrimeNumberDecompositionClient) Recv() (*PrimeNumberDecompositionResponse, error) {
	m := new(PrimeNumberDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberDecompositionServiceServer is the server API for PrimeNumberDecompositionService service.
type PrimeNumberDecompositionServiceServer interface {
	PrimeNumberDecomposition(*PrimeNumberDecompositionRequest, PrimeNumberDecompositionService_PrimeNumberDecompositionServer) error
}

// UnimplementedPrimeNumberDecompositionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberDecompositionServiceServer struct {
}

func (*UnimplementedPrimeNumberDecompositionServiceServer) PrimeNumberDecomposition(req *PrimeNumberDecompositionRequest, srv PrimeNumberDecompositionService_PrimeNumberDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecomposition not implemented")
}

func RegisterPrimeNumberDecompositionServiceServer(s *grpc.Server, srv PrimeNumberDecompositionServiceServer) {
	s.RegisterService(&_PrimeNumberDecompositionService_serviceDesc, srv)
}

func _PrimeNumberDecompositionService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberDecompositionServiceServer).PrimeNumberDecomposition(m, &primeNumberDecompositionServicePrimeNumberDecompositionServer{stream})
}

type PrimeNumberDecompositionService_PrimeNumberDecompositionServer interface {
	Send(*PrimeNumberDecompositionResponse) error
	grpc.ServerStream
}

type primeNumberDecompositionServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *primeNumberDecompositionServicePrimeNumberDecompositionServer) Send(m *PrimeNumberDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberDecompositionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PrimeNumberDecomposition.PrimeNumberDecompositionService",
	HandlerType: (*PrimeNumberDecompositionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _PrimeNumberDecompositionService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "PrimeNumberDecomposition/PrimeNumberDecompositionpb/PrimeNumberDecomposition.proto",
}
