// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Bidi/Bidipb/Bidi.proto

package bidipb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc07ee77fb3d49a, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetEveryoneRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetEveryoneRequest) Reset()         { *m = GreetEveryoneRequest{} }
func (m *GreetEveryoneRequest) String() string { return proto.CompactTextString(m) }
func (*GreetEveryoneRequest) ProtoMessage()    {}
func (*GreetEveryoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc07ee77fb3d49a, []int{1}
}

func (m *GreetEveryoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryoneRequest.Unmarshal(m, b)
}
func (m *GreetEveryoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryoneRequest.Marshal(b, m, deterministic)
}
func (m *GreetEveryoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryoneRequest.Merge(m, src)
}
func (m *GreetEveryoneRequest) XXX_Size() int {
	return xxx_messageInfo_GreetEveryoneRequest.Size(m)
}
func (m *GreetEveryoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryoneRequest proto.InternalMessageInfo

func (m *GreetEveryoneRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetEveryoneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryoneResponse) Reset()         { *m = GreetEveryoneResponse{} }
func (m *GreetEveryoneResponse) String() string { return proto.CompactTextString(m) }
func (*GreetEveryoneResponse) ProtoMessage()    {}
func (*GreetEveryoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebc07ee77fb3d49a, []int{2}
}

func (m *GreetEveryoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryoneResponse.Unmarshal(m, b)
}
func (m *GreetEveryoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryoneResponse.Marshal(b, m, deterministic)
}
func (m *GreetEveryoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryoneResponse.Merge(m, src)
}
func (m *GreetEveryoneResponse) XXX_Size() int {
	return xxx_messageInfo_GreetEveryoneResponse.Size(m)
}
func (m *GreetEveryoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryoneResponse proto.InternalMessageInfo

func (m *GreetEveryoneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "bidi.Greeting")
	proto.RegisterType((*GreetEveryoneRequest)(nil), "bidi.GreetEveryoneRequest")
	proto.RegisterType((*GreetEveryoneResponse)(nil), "bidi.GreetEveryoneResponse")
}

func init() { proto.RegisterFile("Bidi/Bidipb/Bidi.proto", fileDescriptor_ebc07ee77fb3d49a) }

var fileDescriptor_ebc07ee77fb3d49a = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x73, 0xca, 0x4c, 0xc9,
	0xd4, 0x07, 0x11, 0x05, 0x49, 0x60, 0x4a, 0xaf, 0xa0, 0x28, 0xbf, 0x24, 0x5f, 0x88, 0x25, 0x29,
	0x33, 0x25, 0x53, 0xc9, 0x8d, 0x8b, 0xc3, 0xbd, 0x28, 0x35, 0xb5, 0x24, 0x33, 0x2f, 0x5d, 0x48,
	0x96, 0x8b, 0x2b, 0x2d, 0xb3, 0xa8, 0xb8, 0x24, 0x3e, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x33, 0x88, 0x13, 0x2c, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0x24, 0xcd, 0xc5, 0x99, 0x93,
	0x08, 0x93, 0x65, 0x02, 0xcb, 0x72, 0x80, 0x04, 0x40, 0x92, 0x4a, 0x4e, 0x5c, 0x22, 0x60, 0x73,
	0x5c, 0xcb, 0x52, 0x8b, 0x2a, 0xf3, 0xf3, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0xb4, 0xb8, 0x38, 0xd2, 0xa1, 0xe6, 0x83, 0x4d, 0xe4, 0x36, 0xe2, 0xd3, 0x03, 0x59, 0xac, 0x07,
	0xb3, 0x35, 0x08, 0x2e, 0xaf, 0xa4, 0xcf, 0x25, 0x8a, 0x66, 0x46, 0x71, 0x41, 0x7e, 0x5e, 0x71,
	0xaa, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x09, 0xd4, 0x51, 0x50, 0x9e, 0x51,
	0x1a, 0x9a, 0xa5, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x7e, 0x5c, 0xbc, 0x28, 0xe2,
	0x42, 0x52, 0x48, 0x76, 0xa2, 0xb9, 0x50, 0x4a, 0x1a, 0xab, 0x1c, 0xc4, 0x66, 0x25, 0x06, 0x0d,
	0x46, 0x03, 0x46, 0x27, 0x8e, 0x28, 0xb6, 0x24, 0x70, 0xf8, 0x25, 0xb1, 0x81, 0xc3, 0xce, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x56, 0x3b, 0xb4, 0xc9, 0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetEveryoneServiceClient is the client API for GreetEveryoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetEveryoneServiceClient interface {
	GreetEveryone(ctx context.Context, opts ...grpc.CallOption) (GreetEveryoneService_GreetEveryoneClient, error)
}

type greetEveryoneServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetEveryoneServiceClient(cc *grpc.ClientConn) GreetEveryoneServiceClient {
	return &greetEveryoneServiceClient{cc}
}

func (c *greetEveryoneServiceClient) GreetEveryone(ctx context.Context, opts ...grpc.CallOption) (GreetEveryoneService_GreetEveryoneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetEveryoneService_serviceDesc.Streams[0], "/bidi.GreetEveryoneService/GreetEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetEveryoneServiceGreetEveryoneClient{stream}
	return x, nil
}

type GreetEveryoneService_GreetEveryoneClient interface {
	Send(*GreetEveryoneRequest) error
	Recv() (*GreetEveryoneResponse, error)
	grpc.ClientStream
}

type greetEveryoneServiceGreetEveryoneClient struct {
	grpc.ClientStream
}

func (x *greetEveryoneServiceGreetEveryoneClient) Send(m *GreetEveryoneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetEveryoneServiceGreetEveryoneClient) Recv() (*GreetEveryoneResponse, error) {
	m := new(GreetEveryoneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetEveryoneServiceServer is the server API for GreetEveryoneService service.
type GreetEveryoneServiceServer interface {
	GreetEveryone(GreetEveryoneService_GreetEveryoneServer) error
}

// UnimplementedGreetEveryoneServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetEveryoneServiceServer struct {
}

func (*UnimplementedGreetEveryoneServiceServer) GreetEveryone(srv GreetEveryoneService_GreetEveryoneServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetEveryone not implemented")
}

func RegisterGreetEveryoneServiceServer(s *grpc.Server, srv GreetEveryoneServiceServer) {
	s.RegisterService(&_GreetEveryoneService_serviceDesc, srv)
}

func _GreetEveryoneService_GreetEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetEveryoneServiceServer).GreetEveryone(&greetEveryoneServiceGreetEveryoneServer{stream})
}

type GreetEveryoneService_GreetEveryoneServer interface {
	Send(*GreetEveryoneResponse) error
	Recv() (*GreetEveryoneRequest, error)
	grpc.ServerStream
}

type greetEveryoneServiceGreetEveryoneServer struct {
	grpc.ServerStream
}

func (x *greetEveryoneServiceGreetEveryoneServer) Send(m *GreetEveryoneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetEveryoneServiceGreetEveryoneServer) Recv() (*GreetEveryoneRequest, error) {
	m := new(GreetEveryoneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetEveryoneService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bidi.GreetEveryoneService",
	HandlerType: (*GreetEveryoneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetEveryone",
			Handler:       _GreetEveryoneService_GreetEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Bidi/Bidipb/Bidi.proto",
}
