// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AdvanceTopics/Deadlines/greetpb/greet.proto

package greetDeadlinepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7c07ae1a2b8293, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetDeadRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetDeadRequest) Reset()         { *m = GreetDeadRequest{} }
func (m *GreetDeadRequest) String() string { return proto.CompactTextString(m) }
func (*GreetDeadRequest) ProtoMessage()    {}
func (*GreetDeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7c07ae1a2b8293, []int{1}
}

func (m *GreetDeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetDeadRequest.Unmarshal(m, b)
}
func (m *GreetDeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetDeadRequest.Marshal(b, m, deterministic)
}
func (m *GreetDeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetDeadRequest.Merge(m, src)
}
func (m *GreetDeadRequest) XXX_Size() int {
	return xxx_messageInfo_GreetDeadRequest.Size(m)
}
func (m *GreetDeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetDeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetDeadRequest proto.InternalMessageInfo

func (m *GreetDeadRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetDeadResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetDeadResponse) Reset()         { *m = GreetDeadResponse{} }
func (m *GreetDeadResponse) String() string { return proto.CompactTextString(m) }
func (*GreetDeadResponse) ProtoMessage()    {}
func (*GreetDeadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7c07ae1a2b8293, []int{2}
}

func (m *GreetDeadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetDeadResponse.Unmarshal(m, b)
}
func (m *GreetDeadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetDeadResponse.Marshal(b, m, deterministic)
}
func (m *GreetDeadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetDeadResponse.Merge(m, src)
}
func (m *GreetDeadResponse) XXX_Size() int {
	return xxx_messageInfo_GreetDeadResponse.Size(m)
}
func (m *GreetDeadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetDeadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetDeadResponse proto.InternalMessageInfo

func (m *GreetDeadResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greetDeadline.Greeting")
	proto.RegisterType((*GreetDeadRequest)(nil), "greetDeadline.GreetDeadRequest")
	proto.RegisterType((*GreetDeadResponse)(nil), "greetDeadline.GreetDeadResponse")
}

func init() {
	proto.RegisterFile("AdvanceTopics/Deadlines/greetpb/greet.proto", fileDescriptor_ec7c07ae1a2b8293)
}

var fileDescriptor_ec7c07ae1a2b8293 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x5d, 0x0f, 0x4b, 0xfb, 0x64, 0xd1, 0x0d, 0xa2, 0xa2, 0x88, 0x4b, 0x4e, 0xc2, 0x42,
	0x17, 0x76, 0x7f, 0x81, 0x22, 0xe6, 0xe6, 0xa1, 0xee, 0xc9, 0x8b, 0xa4, 0xed, 0xb3, 0x04, 0xd2,
	0x24, 0x26, 0x69, 0x7f, 0xbf, 0x34, 0x6d, 0xa4, 0x05, 0x3d, 0x85, 0x37, 0x33, 0x7c, 0x33, 0x04,
	0xb6, 0x4f, 0x55, 0xc7, 0x55, 0x89, 0x47, 0x6d, 0x44, 0xe9, 0x76, 0x2f, 0xc8, 0x2b, 0x29, 0x14,
	0xba, 0x5d, 0x6d, 0x11, 0xbd, 0x29, 0x86, 0x37, 0x33, 0x56, 0x7b, 0x4d, 0x56, 0xe1, 0x88, 0x19,
	0xfa, 0x0a, 0x09, 0xeb, 0x05, 0xa1, 0x6a, 0x72, 0x0f, 0xf0, 0x25, 0xac, 0xf3, 0x9f, 0x8a, 0x37,
	0x78, 0xb3, 0xd8, 0x2c, 0x1e, 0xd3, 0x3c, 0x0d, 0xca, 0x1b, 0x6f, 0x90, 0xdc, 0x41, 0x2a, 0x79,
	0x74, 0x4f, 0x83, 0x9b, 0xf4, 0x42, 0x6f, 0x52, 0x06, 0x17, 0x2c, 0x82, 0x73, 0xfc, 0x6e, 0xd1,
	0x79, 0x72, 0x80, 0xa4, 0x1e, 0xd9, 0x81, 0x76, 0xb6, 0xbf, 0xce, 0x66, 0xed, 0x59, 0xac, 0xce,
	0x7f, 0x83, 0x74, 0x0b, 0xeb, 0x09, 0xc8, 0x19, 0xad, 0x1c, 0x92, 0x2b, 0x58, 0x5a, 0x74, 0xad,
	0xf4, 0xe3, 0xaa, 0xf1, 0xda, 0x4b, 0xb8, 0x64, 0x53, 0xe0, 0x3b, 0xda, 0x4e, 0x94, 0x48, 0x8e,
	0xb0, 0x9a, 0xe9, 0xe4, 0xe1, 0xaf, 0xe2, 0xc9, 0xd6, 0xdb, 0xcd, 0xff, 0x81, 0x61, 0x03, 0x3d,
	0x79, 0x5e, 0x7f, 0x9c, 0xcf, 0x42, 0xa6, 0x28, 0x96, 0xe1, 0x53, 0x0f, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x67, 0x63, 0xdf, 0x83, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetDeadlineServiceClient is the client API for GreetDeadlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetDeadlineServiceClient interface {
	// Unary Deadline API
	GreetDeadline(ctx context.Context, in *GreetDeadRequest, opts ...grpc.CallOption) (*GreetDeadResponse, error)
}

type greetDeadlineServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetDeadlineServiceClient(cc *grpc.ClientConn) GreetDeadlineServiceClient {
	return &greetDeadlineServiceClient{cc}
}

func (c *greetDeadlineServiceClient) GreetDeadline(ctx context.Context, in *GreetDeadRequest, opts ...grpc.CallOption) (*GreetDeadResponse, error) {
	out := new(GreetDeadResponse)
	err := c.cc.Invoke(ctx, "/greetDeadline.GreetDeadlineService/GreetDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetDeadlineServiceServer is the server API for GreetDeadlineService service.
type GreetDeadlineServiceServer interface {
	// Unary Deadline API
	GreetDeadline(context.Context, *GreetDeadRequest) (*GreetDeadResponse, error)
}

// UnimplementedGreetDeadlineServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetDeadlineServiceServer struct {
}

func (*UnimplementedGreetDeadlineServiceServer) GreetDeadline(ctx context.Context, req *GreetDeadRequest) (*GreetDeadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetDeadline not implemented")
}

func RegisterGreetDeadlineServiceServer(s *grpc.Server, srv GreetDeadlineServiceServer) {
	s.RegisterService(&_GreetDeadlineService_serviceDesc, srv)
}

func _GreetDeadlineService_GreetDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetDeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetDeadlineServiceServer).GreetDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetDeadline.GreetDeadlineService/GreetDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetDeadlineServiceServer).GreetDeadline(ctx, req.(*GreetDeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetDeadlineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetDeadline.GreetDeadlineService",
	HandlerType: (*GreetDeadlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GreetDeadline",
			Handler:    _GreetDeadlineService_GreetDeadline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AdvanceTopics/Deadlines/greetpb/greet.proto",
}
